<?php // BEGIN PHP
$websitekey=basename(__DIR__); if (empty($websitepagefile)) $websitepagefile=__FILE__;
if (! defined('USEDOLIBARRSERVER') && ! defined('USEDOLIBARREDITOR')) {
	$pathdepth = count(explode('/', $_SERVER['SCRIPT_NAME'])) - 2;
	require_once ($pathdepth ? str_repeat('../', $pathdepth) : './').'master.inc.php';
} // Not already loaded
require_once DOL_DOCUMENT_ROOT.'/core/lib/website.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/website.inc.php';
ob_start();
// END PHP ?>
<html lang="fr">
<head>
<title>Support Public - Archidiocèse de Cotonou</title>
<meta charset="utf-8">
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="" />
<meta name="title" content="Support Public - Archidiocèse de Cotonou" />
<meta name="description" content="Interface d'accueil - Portail Support Public" />
<meta name="generator" content="Dolibarr 20.0.2 (https://www.dolibarr.org)" />
<meta name="dolibarr:pageid" content="1" />
<link rel="icon" type="image/png" href="/favicon.png" />
<link rel="canonical" href="/" />
<?php if ($website->use_manifest) { print '<link rel="manifest" href="/manifest.json.php" />'."\n"; } ?>
<!-- Include link to CSS file -->
<link rel="stylesheet" href="/styles.css.php?website=<?php echo $websitekey; ?>" type="text/css" />
<!-- Include link to JS file -->
<script nonce="f2061c45" async src="/javascript.js.php?website=<?php echo $websitekey; ?>"></script>
<!-- Include HTML header from common file -->
<?php if (file_exists(DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html")) include DOL_DATA_ROOT."/website/".$websitekey."/htmlheader.html"; ?>
<!-- Include HTML header from page header block -->

</head>
<!-- File generated by Dolibarr website module editor -->
<body id="bodywebsite" class="bodywebsite bodywebpage-service-support">
<header class="site-header header">
        <div class="container">
            <div class="logo-wrap">
                <div class="row">
                    <div class="col-md-12 site-header-main">
                        <div class="site-logo">
                            <div class="logo-header-inner">
		        	            <?php print '<a href="'.$website->virtualhost.'"> <img class="entry-logo img-responsive" src="/medias/image/service-support/logo-diocese.png" alt="logo" title="logo"></a>'?>
			                </div>
                        </div><!-- end row -->
                    </div> <!-- .col-sm-12 -->
                </div> <!-- .row -->
            </div> <!-- .row -->
        </div> <!-- .container -->
</header>

    <h2>Liste des plateformes des services disponibles de support au public </h2>
    
<div class="container mx-auto">
    
        <!-- Liste des e-services -->
    <?php
        require_once DOL_DOCUMENT_ROOT.'/core/lib/admin.lib.php';
        
        print '<div class="flex flex-wrap justify-between">';
        
        // Requête pour récupérer les entités avec la pagination
        $listentitysql = "SELECT e.rowid, e.label, e.description FROM " . MAIN_DB_PREFIX . "entity e WHERE e.visible <> 2";
        $resql = $db->query($listentitysql);
        
        if ($resql) {
            //récupérer le répertoire des images dans le dossier public pour site web de dolibarr
            $mediafolder = $conf->website->dir_output.'/'.$websitekey;
            // Afficher les éléments de la page
            while ($entity_obj = $db->fetch_object($resql)) {
                
                $urlalt = dolibarr_get_const($db, 'TICKET_URL_PUBLIC_INTERFACE', $entity_obj->rowid);
        
                //les transformations sur les noms des images d'illustrations
                $file_name = $entity_obj->label;
                // 1. Mettre tout en minuscule
                $file_name = strtolower($file_name);
                // 2. Remplacer les espaces et autres caractères blancs par des tirets
                $file_name = preg_replace('/\s+/', '_', $file_name);
        
                print '<div class="w-full md:w-1/3 p-4 flex flex-col justify-between">';
                print '<a href="'.$urlalt.'/index.php?entity='.$entity_obj->rowid.'" target="_blank" class="block bg-gray-200 hover:bg-green-200 rounded-lg shadow-lg transition-all transform hover:scale-105 anim-scroll h-full">';
                print '<div class="relative flex flex-col h-full">';
                print '<img src="'.'/medias/image/'.$websitekey.'/'.$file_name.'.png" alt="'.$entity_obj->label.'" class="w-full h-32 object-contain rounded-t-lg">';
                print '<div class="absolute top-0 left-0 right-0 bottom-0 bg-green-500 opacity-50 rounded-t-lg"></div>';
                print '<div class="relative p-4 flex-grow">';
                print '<h3 class="text-green-600 font-bold text-lg">'.$entity_obj->label.'</h3>';
                print '<p class="text-black mt-2">'.$entity_obj->description.'</p>';
                print '<span class="text-green-600 font-bold underline">'.$urlalt.'</span>';
                print '</div>';
                print '</div>';
                print '</a>';
                print '</div>';
            }
        }
    ?>
        
    
  </div>
</body>
</html>
<?php // BEGIN PHP
$tmp = ob_get_contents(); ob_end_clean(); dolWebsiteOutput($tmp, "html", 1); dolWebsiteIncrementCounter(1, "page", 1);
// END PHP ?>
