-- Copyright (C) 2024	Frédéric Hounkponou	<omegajunior.apps@gmail.com>
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see https://www.gnu.org/licenses/.

-- to drop index categorie if its do exist
--DROP INDEX uk_eservices_categorie_label ON llx_categorie;
-- to prevent an additionnal insert of categorie if its do exist on the entity
ALTER TABLE llx_categorie ADD UNIQUE INDEX uk_eservices_categorie_label(label);
-- to prevent an additionnal insert of categorie if its do exist on the entity
--ALTER TABLE llx_categorie ADD UNIQUE INDEX uk_eservices_categorie_entity_label(entity,label);